### ISSUE TITLE
Internal server error bug when 400+ requests

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#182]
**Context**

- Log: (psycopg2.OperationalError) connection to server at "34.27.217.4", port 5432 failed: FATAL:  remaining connection slots are reserved for non-replication superuser connections
- Connection metrics from GCP at the time of the issue 
<img width="400" alt="Screenshot 2023-11-25 at 2 19 57 PM" src="https://github.com/MobilityData/mobility-feed-api/assets/90632321/4bb736d3-b181-486f-b6b0-6c00b00615ce">

**Possible Solutions**
- Load API test

**Comment by qcdyx** [comment]
Max_connection is already set to 100.
![image](https://github.com/MobilityData/mobility-feed-api/assets/5789435/ee037835-2045-4b93-8b95-4aa5d22f2e3c)

**Comment by qcdyx** [comment]
https://github.com/MobilityData/mobility-feed-api/issues/219 We should optimize the code to use a global session.

**Comment by qcdyx** [comment]
the Locust web UI does not provide a feature to download API responses. The purpose of Locust is to simulate users and load test your application, not to inspect individual API responses.

**Comment by qcdyx** [comment]
Active connection is 4 after using a global session (Ramping to 2000 users at a rate of 100.00 per second). It was 98 prior to the change. Details is shared in the Load Test Action Plan.

**Comment by qcdyx** [comment]
![Image](https://github.com/MobilityData/mobility-feed-api/assets/5789435/288e19eb-a817-40c4-b631-a03ae043cd77)

**Comment by qcdyx** [comment]
Further Steps of Mobility Database API Load Test:

1. Check if the request/response is correct: You need to ensure that the request you're sending in your load test is correctly formatted and that the server's response is as expected. This might involve checking the request headers, body, and URL, as well as the status code and body of the server's response.

2. Adjust rate limit to prevent 429 Too Many Requests: This status code indicates that the user has sent too many requests in a given amount of time ("rate limiting"). The response representations SHOULD include details explaining the condition, and MAY include a Retry-After header indicating how long to wait before making a new request. This is used in rate limiting scenarios and is part of HTTP/1.1 standard: If you're getting 429 errors, it means you're sending requests too quickly. You can adjust the rate of requests in your load test by changing the wait_time attribute of your HttpUser class, or by reducing the number of users or spawn rate when you run the test.
3. HTTP status code 403 means "Forbidden". This status code indicates that the client does not have the necessary permissions to access the requested resource: If you're getting 403 errors, it means the server is rejecting your requests due to a lack of permission. You might need to include an Authorization header with a valid token in your requests, or ensure that the user associated with that token has the necessary permissions on the server.
