### ISSUE TITLE
Test batch processing workflows in production

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#233]
Test if 

- Historical dataset process works
- Adding and updating feeds work
- Bounding box extraction

Use cases: 

- No authentication
- Authentication
- GTFS Schedule
- GTFS Realtime

How to test 

- Update prod
- Check if recent commits in the catalogs repo (e.g https://github.com/MobilityData/mobility-database-catalogs/commit/3fe6c0da6fa605db51b3e17067a0920406a284b0) and (https://github.com/MobilityData/mobility-database-catalogs/commit/8eeb884842e61ffbfbbf3eea356dd48421ea6d9a) are reflected in the prod database

**Comment by cka-y** [comment]
There's an ongoing issue regarding security and performance impacts due to hacking attempts on our PostgreSQL database (#192). Given that this might affect the testing process for the historical dataset and feed updates, I suggest we wait until this security issue is resolved. This way, we can avoid overlapping work and ensure accurate test results.
