### ISSUE TITLE
Production bugs

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#269]
### Describe the bug

Issues uncovered from #233 

- Tokens API: I had to put a dummy value for secret PROD_FEEDS_GCP_IDP_API_KEY for the API deploy to complete -- not sure where this value is set, but since it's not right, the tokens api does not currently work
- API: With a proper access token, I get response Invalid IAP credentials: JWT signature is invalid
- Web APP: The sign in method using google or github does not work, however using email works fine

### Steps/Code to Reproduce

Add here

### Expected Results

Tokens API works correctly
Access token successful
Single sign on works

### Actual Results

See above.

**Comment by davidgamez** [comment]
Unfortunately, the fixes are part of manual steps for _new_ environments related to the Firebase project setup.
- PROD_FEEDS_GCP_IDP_API_KEY, is coming from the firebase-generated token that is located in the _Credentials_ page of Google console
- Web API is failing due to the domain that need to be added as a _authorized domain_ into the firebase project settings
- API: might be related to PROD_FEEDS_GCP_IDP_API_KEY

**Comment by davidgamez** [comment]
Let's address documentation on #270
