### ISSUE TITLE
Trim spaces in the location fields and regenerate location ids

### ISSUE THREAD

**Issue by davidgamez** [MobilityData/mobility-feed-api#318]
# Description

Some location IDs in the location table contain a `_` at the end. The municipality may have ending spaces. Example: US-Washington-Wenatchee_

# Proposed solution
Trim spaces at the beginning and end of the municipality values. As part of this issue, we should also trim spaces in country_code and subdivision_name to avoid the same problem.

**Comment by emmambd** [comment]
Tasks: 

- Identify all feeds with missing municipality and/or subdivision field (2 underscores in the middle, underscore at beginning or end) 
- Modifying the concatenation code in populate script to trim 
- Update database (manually or Liquibase) 

Resources: 

update database script locally

**Comment by davidgamez** [comment]
Blocked by #402

**Comment by jcpitre** [comment]
Because the dash is a legitimate character in subdivision-name. and municipality, it is suggested to change the separator to a character that will be disallowed when setting the data. For example `|`

Question: Why is it a problem with is ending with the separator (for |, example is `US|New-York|`
Or have 2 separators after the other. e.g. `US||`
That is as good an ID as any other, plus it conveys some info.

**Comment by jcpitre** [comment]
In the current DEV db, there are:

- 5 subdivision_name starting or ending with a space
- 6 municipalities starting or ending with a space.

**Comment by jcpitre** [comment]
Blocked until after release.
We will then have to remove entries in the location table by hand

**Comment by jcpitre** [comment]
Deleted 15 unused locations by hand in PROD.
