### ISSUE TITLE
Investigate current dataset updates + hashing

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#408]
We know sometimes new datasets are being added to a feed even though there are no changes to the actual file contents. 

The scope of this issue is to query to identify how many feeds are pushing dataset updates when the file contents don't change, and suggest an approach for how we can improve this in the future. 

Discussed possible improvements: 

- Unzip the GTFS feed and check the files date change rather than just on the ZIP

**Comment by cka-y** [comment]
Tasks:
- [ ] Query to see how often feeds are updated 
- [ ] Compare feeds that are often updated using Pandas DataFrame (one time script), https://transport.data.gouv.fr/tools/gtfs_diff or other tools
- [ ] Propose a solution for hashing if needed

**Comment by cka-y** [comment]
## Findings: Investigation of Current Dataset Updates and Hashing

### Results
After analyzing the current dataset updates and hashing processes, none of the updates appear to be invalid. This means that for each new dataset downloaded, at least one of the relevant GTFS files in the zipped folder has changed. These files include agency.txt, stops.txt, routes.txt, and more, as listed below (see Graph 3). Note that `locations.geojson` was excluded from this analysis for simplicity, and since none of the datasets currently contain it, omitting it has no effect.

**Graph 1: Distribution of Days Between Updates**
The graph below shows that most updates occur every 5-9 days, aligning with the weekly `batch-processing` job schedule. Over 30% of weekly updates are error updates due to "unzippable folder" errors, where the producer URL responds, but the response isn't a zipped folder. [Here's a list of all current error datasets](https://github.com/MobilityData/mobility-feed-api/files/15238726/unzippable_datasets.csv) (note that this list will change as the weekly `batch-processing` job adds more datasets). Updates occurring less than six days apart are due to manually triggered batch processing and can be excluded from consideration in this analysis.

![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/5a1e9f89-e206-4764-be45-c6f25c12c140)

**Graph 2: Top 300 Most Updated Feeds**
The second graph shows the 300 most frequently updated feeds. It's notable that some of these feeds are consistently error-prone and still updated. Some feeds only occasionally return errors, while others always produce "unzippable" errors.

![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/122e0228-ae64-4fe0-8a4b-75dc9684c1f2)

**Graph 3: Files Updated Between Subsequent Datasets**
The pie chart below displays the proportion of GTFS files updated between subsequent datasets.

![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/17972d6b-f23f-4cd8-a2ea-bb80540f7f1d)

### Conclusion
Since all datasets are valid, there's no immediate need to develop a new hashing method, as the current one is adequate. However, to avoid processing non-zipped datasets and providing invalid data through the API, an additional validation check should be added to the `batch-processing` job to ensure that the dataset is a zipped file. If it's not, the job should stop processing, reducing unnecessary costs and preventing the distribution of invalid data.

A long-term goal should involve tracking errors and monitoring the logic related to dataset additions, so that issues can be detected and addressed promptly.

**Comment by emmambd** [comment]
@cka-y This is gold! We can consider the investigation complete. 

Let's make sure to add reviewing Graph #2 and doing a deep dive on feeds that only occasionally return unzippable errors as part of the "next step" issue - so we're making sure to understand how common it is for a feed to return no dataset whatsoever and then start to run successfully again.

**Comment by emmambd** [comment]
@cka-y I now understand why we were always pulling data that actually changed - because we were only updating active feeds ;) 

This analysis likely needs to be re-done after https://github.com/MobilityData/mobility-database-catalogs/issues/375 is open for a month.

**Comment by cka-y** [comment]
## Round 2 of Findings: Investigation of Current Dataset Updates and Hashing

### Results

After analyzing the current dataset updates and hashing processes, none of the datasets appear to be invalid. This means that for each new dataset downloaded, at least one file in the zipped folder has changed. The difference with the previous findings is that we now have no problematic feeds (i.e., feeds that we are unable to unzip) due to changes introduced in #471, including manual cleanup.

**Graph 1: Distribution of Days Between Updates**  
The graph below shows that most updates (~73%) occur every 0-9 days, aligning with the weekly `batch-processing` job schedule.  
![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/0173c637-bb81-4166-92ca-abe1699555d5)

**Graph 2: Top 300 Most Updated Feeds**  
The second graph shows the 300 most frequently updated feeds.  
![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/1960c826-4958-4d70-9108-b6757a94cdfe)

**Graph 3: GTFS Files Updated Between Subsequent Datasets**  
The pie chart below displays the proportion of GTFS files updated between subsequent datasets.  
![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/1d4ea750-9556-44c2-850f-f9f07dee4693)

**Graph 4: Files Updated Between Subsequent Datasets**  
This graph is included for informational purposes to compare the updates of GTFS files against non-GTFS files. It appears that non-GTFS files, such as `timetables.txt`, `stop_attributes.txt`, and `emissions.txt`, are updated more frequently than the most updated GTFS file (`feed_info.txt`).  
![Image](https://github.com/MobilityData/mobility-feed-api/assets/60586858/f3f1541e-31f8-4e86-a838-ef286ad780c0)

### Conclusion

Since all dataset updates are valid, there's no immediate need to develop a new hashing method, as the current one is adequate. Avoiding the processing of invalid zip folders has proven to be a significant improvement.
