### ISSUE TITLE
Automate location generation

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#618]
### Describe the problem

Defined in #564

### Proposed solution

**Methodology:**
A sample of 5 stops is extracted from the `stops.txt` file. If more than half of the sampled stops within a feed have different municipalities or subdivisions, these specific values are not considered in determining the feed's location and are set to `None`. However, if the feed includes multiple countries, the list of all countries is included in the feed's location information.

- To test that it works
    - I can input full country name and return a series of results 
    - I can input a location name without accents and it works

**Comment by emmambd** [comment]
@emmambd to adjust UI design to incorporate multiple countries

**Comment by cka-y** [comment]
Tasks:
1. **Modify the database entity** to support multiple languages.
2. **Add a link between the `Location` entity and the `GTFSDataset` entity**, as the location will now be extracted from the bounding box of the dataset.
3. **Modify/set the location in the datasets** by calling the Nominatim API in both the default and English languages. This can be done as part of the `extract_bb` cloud function, which could be renamed to `extract_location`.
4. **Modify the API response for the feed** to set the location as the latest dataset location if that dataset exists; otherwise, resort to the location information extracted from the `mobility-database-catalog`.
5. **Modify the materialized view utilized by the search endpoint** to fix issues related to searching for locations in English.
